export const AI_PROVIDER_GEMINI = 'gemini';
export const AI_PROVIDER_GROQ = 'groq';

export const SUPPORTED_AI_PROVIDERS = [AI_PROVIDER_GEMINI, AI_PROVIDER_GROQ] as const;

export type AIProvider = (typeof SUPPORTED_AI_PROVIDERS)[number];

export const DEFAULT_AI_CHAT_PRIMARY_PROVIDER: AIProvider = AI_PROVIDER_GROQ;
export const DEFAULT_AI_SUMMARY_PRIMARY_PROVIDER: AIProvider = AI_PROVIDER_GROQ;
export const DEFAULT_AI_CHAT_FALLBACK_ENABLED = true;
export const DEFAULT_AI_SUMMARY_FALLBACK_ENABLED = true;
export const DEFAULT_AI_GROQ_HISTORY_LIMIT = 6;
export const DEFAULT_AI_GROQ_MAX_INPUT_TOKENS = 6000;
export const DEFAULT_AI_GROQ_MAX_MATCHING_JOBS = 3;
export const DEFAULT_AI_GROQ_MAX_SEARCH_RESULTS = 3;
export const DEFAULT_AI_GROQ_MAX_COMPANY_ITEMS = 2;
export const DEFAULT_AI_GROQ_MAX_TOP_SKILLS = 5;
export const DEFAULT_AI_GROQ_MAX_TOP_COMPANIES = 5;
export const DEFAULT_AI_GROQ_MAX_SUMMARY_CHARS = 400;
